### ISSUE TITLE
indexing in rsa.py when events are not range(0,nConditions-1)

### ISSUE THREAD

**Issue by iancharest** [mvdoc/meegnobis#3]
does the code assume that unique targets range from 0 to nconditions -1?
does it need to be?

**Comment by iancharest** [comment]
this is also true for line 39 I think

**Comment by iancharest** [comment]
and line 59

**Comment by iancharest** [comment]
also, does this code assume that unique targets range from 0 to nconditions -1?
maybe that's what the hiccup is. (but nevertheless there should defo be 2556 rows in the vectorised rdms.)

**Comment by iancharest** [comment]
ok, the problem might not be with the length but the problem might be with the fact that my events are 11:82, and not 1:72 (or 0:71). 

this leads to a problem, starting at line 109 of rsa.py:

for ipair, (p1, p2) in enumerate(
                _get_combinations_triu(unique_targets)):
            log.info("Running for pair number {0} ({1}, {2})".format(ipair,
                                                                     p1, p2))
            if p1 != p2:
                mask_train, mask_test = _get_mask_binary_trials(p1, p2,
                                                                targets_train,
                                                                targets_test)

because 

def _get_combinations_triu(unique_targets):
    n_unique_targets = len(unique_targets)
    for p1 in range(n_unique_targets):
        for p2 in range(p1, n_unique_targets):
            yield unique_targets[p1], unique_targets[p2]

yields 11 when p1 is 0 

and then when calling _get_mask_binary_trials with target1 being yielded in as 11, you try to index unique_targets[11] instead of indexing unique_targets[0]  

def _get_mask_binary_trials(target1, target2, targets_train, targets_test):
    unique_targets = _get_unique_targets(targets_train, targets_test)
    target1 = unique_targets[target1]
    target2 = unique_targets[target2]
    mask_train = (targets_train == target1) | \
                 (targets_train == target2)
    mask_test = (targets_test == target1) | \
                (targets_test == target2)
    return mask_train, mask_test

pretty sure that is a bug.

**Comment by iancharest** [comment]
ok. i think I fixed this. 

```def _get_combinations_triu(unique_targets):
    n_unique_targets = len(unique_targets)
    for p1 in range(n_unique_targets):
        for p2 in range(p1, n_unique_targets):
            yield unique_targets[p1], unique_targets[p2]
```
```
def _get_indices_triu(unique_targets):
    n_unique_targets = len(unique_targets)
    for p1 in range(n_unique_targets):
        for p2 in range(p1, n_unique_targets):
            yield p1, p2
```

so that we can call _get_indices_triu(unique_targets) when we want to index our epochs:

```
for ipair, (p1, p2) in enumerate(
                _get_indices_triu(unique_targets)):
            log.info("Running for pair number {0} ({1}, {2})".format(ipair,
                                                                     unique_targets[p1], unique_targets[p2]))
            if p1 != p2:
                mask_train, mask_test = _get_mask_binary_trials(p1, p2,
                                                                targets_train,
                                                                targets_test)
```
and later on, in _compute_fold you really want to return the actual triggers:
```
...
targets_pairs = []
    for tr_lbl, te_lbl in _get_combinations_triu(unique_targets):
        targets_pairs.append('+'.join(map(str, [tr_lbl, te_lbl])))

    return rdms, targets_pairs
```

**Comment by mvdoc** [comment]
I will check this tomorrow, but yes generally the assumption is that
targets are between 0 and n-1. This is because I got a bug in scikit learn
once when having multidimensional targets, and the safest option is to keep
targets as integers. One can easily convert to the right format using
scikit learn's labelencoder. I will post an example and change the docstring

**Comment by mvdoc** [comment]
OK so I modified the code to allow arbitrary encoding of the targets, and it's now updated on master (https://github.com/mvdoc/meegnobis/commit/3af0c0e643950e8c720cedd054eb44df2b35ad1e). I wrote some tests and it should work, would you mind trying it out?

Thanks!
Matteo

**Comment by iancharest** [comment]
works now.

**Comment by mvdoc** [comment]
great! closing this
